language: node_js
node_js:
  - "8.9.4"
script: git push --dry-run https://github.com/marcosbozzani/burguer HEAD:ci-integration
#deploy:
#  provider: script
#  skip_cleanup: true
#  script:
#    - yarn run semantic-release
  


