language: node_js
node_js:
  - 10

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
      
  - provider: releases
    api_key: $GH_TOKEN
    skip_cleanup: true
    on:
      tags: true
